# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Run Tests"
  lane :unit_test do
    puts "Running WMarkdown Tests"

    sh("rm", "-rf", "../fastlane/test_output/")

    scan(
      package_path: ".", # This makes swift package testing possible without a pbxproj or xcworkspace file
      scheme: "WMarkdown", # Needs "-Package" at the end 
      clean: true,
      device: "iPhone 14 Pro", # This is needed for a proper destination
      output_types: 'junit',
      output_files: 'junit.xml',
      result_bundle: true, # Other errors with xcoutput required me to add this
      output_directory: Dir.pwd + "/test_output"
    )
  end
end
