name: Check PR

on:
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3
      - name: List available devices
        run: xcrun simctl list devicetypes 
      - name: Build and run tests
        run: xcodebuild test -scheme WMarkdown -destination 'platform=iOS Simulator,name=iPhone 14 Pro'

